// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/content-scripts/developerActivityOpenrankTrends.js"
    | "/content-scripts/developerHovercardInfo.js"
    | "/content-scripts/developerNetworks.js"
    | "/content-scripts/gitee.js"
    | "/content-scripts/github.js"
    | "/content-scripts/perceptorLayout.js"
    | "/content-scripts/perceptorNavTab.js"
    | "/main.png"
    | "/openDiggerLogo.png"
    | "/options.html"
    | "/osGraphLogo.png"
    | "/popup.html"
    | "/rocketDarkLogo.png"
    | "/rocketLightLogo.png"
    | "/sandbox.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
