# This yml is adapted from pull_request_test_build.yml
name: build

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - "master"
  pull_request:
    branches:
      - "*"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build
        run: |
          yarn install
          npm run build
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Format checks
        run: |
          yarn install
          npm run prettier:check

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      # Generate packages in Release
      - name: Release
        uses: softprops/action-gh-release@v1
    needs: [build, checks]


