# deploy.yml
# deploy the selected tag to stores
name: deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Input a new version number to release. (e.g. 1.2.3)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: "yarn"

      - name: Check Version
        run: |
          echo "check version"

      - name: Build
        run: |
          yarn install
          yarn run build

      - name: Zip to hypercrx.zip
        run: zip -j release/hypercrx.zip build/*

      - name: Append version to release file names
        run: |
          cp release/hypercrx.crx ${{format('release/hypercrx-{0}.crx', github.event.inputs.version)}}
          cp release/hypercrx.zip ${{format('release/hypercrx-{0}.zip', github.event.inputs.version)}}

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/hypercrx-v*.*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}
          generateReleaseNotes: true

      - name: Deploy
        run: |
          yarn run deploy
        env:
          CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          EDGE_PRODUCT_ID: ${{ secrets.EDGE_PRODUCT_ID }}
          EDGE_CLIENT_ID: ${{ secrets.EDGE_CLIENT_ID }}
          EDGE_CLIENT_SECRET: ${{ secrets.EDGE_CLIENT_SECRET }}
          EDGE_ACCESS_TOKEN_URL: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}
